---
title: "Agent Names"
description: "Randomly assigned personalities for running Claude agents"
icon: "user"
---

When a task starts running, Claude Board assigns it a random agent name from a pool of 30 character names. This gives each running agent a distinct personality.

## Name Pool

Names include: Nova, Atlas, Spark, Echo, Pulse, Drift, Flux, Blaze, Cipher, Nexus, Orbit, Prism, Surge, Volt, Apex, Helix, Pixel, Byte, Quark, Zephyr, Onyx, Jade, Iris, Sol, Astra, Cosmo, Flare, Rune, Vega, Luna.

## Where Names Appear

- **Agent Cards** in the orchestration sidebar — avatar + bold name
- **Battle View** — name tag above each agent sprite
- **Terminal logs** — "Agent Nova starting task: Login redesign"
- **Speech bubbles** — last tool call shown in a cute bubble below the avatar

## Avatars

Each agent gets a unique avatar generated by [boring-avatars](https://boringavatars.com) using the "beam" variant. Since avatars are deterministic based on the name, the same agent name always produces the same avatar.

## Storage

Agent names are stored in the `agent_name` column on the tasks table and persist across restarts.
